### ISSUE TITLE
macOS installation instructions incomplete

### ISSUE THREAD

**Issue by MikeTheCanuck** [zeek-packages/zeek-agent-v2#14]
The primary instruction says:
> To install, open the DMG disk image, copy the `Zeek Agent` installer application into your system's /Applications folders, and execute it there.

After downloading the latest macOS release [https://github.com/zeek/zeek-agent-v2/releases/download/v2.2.0/zeek-agent-2.2.0-macos11.tar.gz](here), I couldn't be sure I got this properly working on my MBP 13.6.3 box:

1. Didn't find a DMG file when un-`tar`ing the downloaded file
2. Explored the resulting folders, didn't find a `Zeek Agent` file.
3. Thought maybe the `/bin/zeek-agent` file might be the intended target, so tried running it as normal user; the `[warning] not running as root, information may be incomplete` was ambiguous; not sure if this means it's still running but unable to record, running and recording but missing most of the interesting bits, or running and recording (which types of activities are being recorded?).
4. I saw no output nor mention in the docs (a) under what conditions user needs to manually enable system permissions or (b) what permissions need to be enabled and where in System Settings.

**Comment by rsmmr** [comment]
2.2 is a legacy release that doesn't use the DMG installer yet. The DMG installer is created by the current development version, which is what the README is describing (there's a note along those but it's easy to miss admittedly). But thanks for the nudge, it's time to push a 2.3 release, I'll do that shortly.

**Comment by rsmmr** [comment]
2.3.0 is now released, with new artifacts that match what the instructions say, see https://github.com/zeek/zeek-agent-v2/releases/tag/v2.3.0
